package edu.ncsu.csc.iTrust2.repositories;

import org.springframework.data.jpa.repository.JpaRepository;

import edu.ncsu.csc.iTrust2.models.CovidVaccine;

/**
 * Repository for interacting with CovidVaccine model. Method implementations
 * generated by Spring
 *
 * @author Jack Randle
 *
 */
public interface CovidVaccineRepository extends JpaRepository<CovidVaccine, Long> {
    /**
     * Check if a CovidVaccine exists with the given code
     *
     * @param code
     *            Code to search by
     * @return If the CovidVaccine exists
     */
    public boolean existsByCode ( String code );

    /**
     * Find a CovidVaccine by the given code
     *
     * @param code
     *            Code to search by
     * @return The CovidVaccine, if it exists
     */
    public CovidVaccine findByCode ( String code );
}
