package edu.ncsu.csc.iTrust2.repositories;

import java.util.List;

import org.springframework.data.jpa.repository.JpaRepository;

import edu.ncsu.csc.iTrust2.models.User;
import edu.ncsu.csc.iTrust2.models.VaccineAppointmentRequest;

/**
 * Repository for interacting with VaccineAppointmentRequest model. Method
 * implementations generated by Spring
 *
 * @author Sai Maale
 *
 */
public interface VaccineAppointmentRequestRepository extends JpaRepository<VaccineAppointmentRequest, Long> {

    /**
     * Find all VaccineAppointmentRequests for the provided Patient
     *
     * @param patient
     *            Patient to find ARs for
     * @return Matching ARs
     */
    public List<VaccineAppointmentRequest> findByPatient ( User patient );

    /**
     * Find all vaccine appointment requests for a given HCP
     *
     * @param hcp
     *            HCP for lookups
     * @return Matching requests
     */
    public List<VaccineAppointmentRequest> findByHcp ( final User hcp );

    /**
     * Find all vaccine appointment requests for a given HCP and patient
     *
     * @param hcp
     *            HCP for lookups
     * @param patient
     *            Patient for lookups
     * @return Matching requests
     */
    public List<VaccineAppointmentRequest> findByHcpAndPatient ( final User hcp, final User patient );

}
